### ISSUE TITLE
Compiling Error

### ISSUE THREAD

**Issue by benmatz** [theGrue/jeopardy#7] opened 2021-07-30 18:18 UTC
I am also having a very similar issue where it outputs this when I do`node app.js`

```
/Users/ben/Downloads/jeopardy/app.js:19
var io = require('socket.io').listen(server);
                              ^

TypeError: require(...).listen is not a function
    at Object.<anonymous> (/Users/ben/Downloads/jeopardy/app.js:19:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```
I have v14.17.3 FYI. Thanks!

**Comment by theGrue** [comment] 2021-07-30 19:47
Duplicate of #6, closing.

**Closed as completed by theGrue** 2021-07-30 19:47 UTC
